Numpy - Used for scientific calculation

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[1]

2

## Well I already have a list, why would i need numpy..

##### 3 Benefits of numpy array over python list
1. Less memory
2. Fast
3. Convinient 

In [10]:
#Less memory
l = range(1000)
import sys
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size * array.itemsize) #Results in bytes
# 1 element = 4 bytes in numpy
# 1 object = 14 bytes

28000
4000


## Basic array operations

In [11]:
 arr = np.array([5,6,9]) #Create one dimentional array

In [43]:
arr2 = np.array([[1,2],[3,4],[8,9]]) #Create two dimentional array

In [44]:
arr

array([5.+0.j, 6.+0.j, 9.+0.j])

In [45]:
arr.ndim

1

In [46]:
arr2

array([[1, 2],
       [3, 4],
       [8, 9]])

In [47]:
arr2.ndim

2

In [48]:
arr.itemsize #integer has 4 bytes

16

In [49]:
arr.dtype

dtype('complex128')

In [50]:
 arr = np.array([5,6,9], dtype=np.float64)

In [51]:
arr.itemsize #float numbers occupy 8bytes

8

In [52]:
arr.size #total number of elements

3

In [53]:
arr.shape #dimensions like lenght and breath 

(3,)

In [54]:
arr2.shape

(3, 2)

In [55]:
arr = np.array([5,6,9], dtype=complex)
arr

array([5.+0.j, 6.+0.j, 9.+0.j])

In [56]:
#For initializing the array with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
l = range(5)
l

range(0, 5)

In [59]:
np.arange(1,5)


array([1, 2, 3, 4])

In [60]:
np.arange(1,10, 2) # add step of 2

array([1, 3, 5, 7, 9])

In [61]:
np.linspace(1,5,10) #It generates 10 numbers between 1 to 5 with linear space

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [62]:
arr2.shape

(3, 2)

In [63]:
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 8, 9]])

In [64]:
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [8],
       [9]])

In [66]:
arr2.ravel() #Makes one dimensionali.e returns new array but donot modify

array([1, 2, 3, 4, 8, 9])

In [68]:
arr2.min()

1

In [69]:
arr2.max()

9

In [70]:
arr2.sum()

27

In [72]:
arr2.sum(axis=0) #each columns gets summed up

array([12, 15])

In [73]:
arr2.sum(axis=1)

array([ 3,  7, 17])

In [75]:
np.sqrt(arr2) #Computes square root of each element

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.82842712, 3.        ]])

In [76]:
np.std(arr2) #standard deviation

2.9860788111948193

In [77]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [78]:
a+b

array([[ 6,  8],
       [10, 12]])

In [79]:
a-b

array([[-4, -4],
       [-4, -4]])

In [80]:
a*b

array([[ 5, 12],
       [21, 32]])

In [81]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [82]:
# for martrix product
a.dot(b)

array([[19, 22],
       [43, 50]])

## Slicing/stacking arrays, Indexing with boolean array

### Indexing and slicing

In [83]:
a = np.array([6,7,8])

In [84]:
a[0:2] #Slicing

array([6, 7])

In [86]:
a[-2] # Reverse indexing

7

In [87]:
a2 = np.array([[1,2,3], [3,4,5], [9,3,2]])
a2

array([[1, 2, 3],
       [3, 4, 5],
       [9, 3, 2]])

In [89]:
a2[1,2] # 2nd row , 3 column

5

In [92]:
a2[0:2, 2] #a2[row, column]

array([3, 5])

In [93]:
a2[-1]

array([9, 3, 2])

In [94]:
a2[-1, 0:2]

array([9, 3])

In [95]:
a2[:,1:3 ]

array([[2, 3],
       [4, 5],
       [3, 2]])

In [96]:
a2

array([[1, 2, 3],
       [3, 4, 5],
       [9, 3, 2]])

In [97]:
for row in a2:
    print(row)

[1 2 3]
[3 4 5]
[9 3 2]


In [99]:
for cell in a2.flat:
    print(cell) #flattens in to 1D

1
2
3
3
4
5
9
3
2


In [100]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [101]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [102]:
np.vstack((a,b)) #Vertical stacking

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [104]:
np.hstack((a,b)) #Horizontal stack

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [106]:
a= np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [107]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [108]:
result = np.hsplit(a,3)

In [109]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [110]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [111]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [113]:
result = np.vsplit(a,2)

In [114]:
result 

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [115]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [116]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### Indexing with boolean array

In [118]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
b = a>4 #Evaluates each elements
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [123]:
a[b] #Looked at b array, and returned the element where it is defined as True

array([ 5,  6,  7,  8,  9, 10, 11])

In [124]:
a[b] = -1 #Replaced based on condition

In [125]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

## Iterate numpy array using nditer

In [126]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [131]:
for row in a.flatten():
        print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [133]:
for x in np.nditer(a, order='C'):
    print(x) 
# order = c : C order
# order = F : Fortran order

0
1
2
3
4
5
6
7
8
9
10
11


In [134]:
for x in np.nditer(a, order='F'):
    print(x) 

0
4
8
1
5
9
2
6
10
3
7
11


In [137]:
for x in np.nditer(a, order='F', flags=['external_loop']):
    print(x) # prints entire column

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [138]:
for x in np.nditer(a, op_flags=["readwrite"]):
    x[...] = x*x

In [140]:
a #Original array is square of previous 

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [145]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [147]:
for x, y in np.nditer([a,b]):
    print(x, y) #iterating thruogh 2 arrays

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
